name: Use Secret Key

on: 
  push:
    branches:
      - master

jobs:
  use-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.3.1'

    - name: Install dependencies
      run: npm install

    - name: Use secret key
      run: |
        echo "Using secret key in the environment"
        echo "ATLASSIAN_API_KEY: $ATLASSIAN_API_KEY"
      env:
        ATLASSIAN_API_KEY: ${{ secrets.ATLASSIAN_API_KEY }}
